### ISSUE TITLE
`site-header` ning tepa qismidagi rasm qo'yilishi kerak

### ISSUE THREAD

**Issue by darxanov** [Muhammadumar2002/Jobs-listings#1]
Sizdagi holat: 
![image](https://user-images.githubusercontent.com/99054718/167568497-0e26f394-facc-47cf-98b9-8d2ddd29e67c.png)
Maketdagi holat: 
![image](https://user-images.githubusercontent.com/99054718/167568957-5f9d94d1-416d-4df3-baa7-fe9015aaa6ba.png)

**Comment by Muhammadumar2002** [comment]
Yana bir tekshirib ko'rasizmi
