### ISSUE TITLE
Classlar orasida joy tashlashda har xillikka yo'l qo'yilgan ya'ni ba'zi classlar orasida bo'sh qator qoldirilmagan, ba'zi classlar orasida 4 qator  bo'sh qoldirilgan.

### ISSUE THREAD

**Issue by NodirXon0609** [Muhammadumar2002/Jobs-listings#2]
195-qatordagi class bilan 200-qatordagi classlar orasida, 233-qatordagi class bilan 236-qatordagi classlar orasida, 256-qatordagi class bilan 260-qatordagi classlar orasida, 274-qatordagi class bilan 277-qatordagi classlar orasida bo'sh joy qoldirilmagan, kamida bittta bo'sh qator qoldirilsa classlar bir biridan farqlanib turar edi, bu  esa ko'dingizni tashqi ko'rinishiga ta'sir qilyapdi.
260-qatordagi class bilan 274-qatordagi class orasida esa bo'sh qatorlar soni ko'payib ketgan.

**Comment by Muhammadumar2002** [comment]
Fixed
