### ISSUE TITLE
job-listing-item class'iga berilgan background-color, body ni background-color'i bilan bir xil bo'lib qolgan. job-listing-item class'ini background-color: #fff bo'lishi kerak.

### ISSUE THREAD

**Issue by NodirXon0609** [Muhammadumar2002/Jobs-listings#3]
Hozirgi holati:
![image](https://user-images.githubusercontent.com/99398673/168168353-4e92fbc7-e4b2-4619-b2a1-d7a08d7750d2.png)

Maketdagi holat:
![image](https://user-images.githubusercontent.com/99398673/168168467-c1cd075d-69aa-4557-b633-2a7501e96d83.png)

**Comment by Muhammadumar2002** [comment]
Fixed
